"""empty message

Revision ID: b7462591bfa1
Revises: de7e57b0afb1
Create Date: 2020-08-02 22:12:30.474566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7462591bfa1'
down_revision = 'de7e57b0afb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'end_date')
    # ### end Alembic commands ###
